<<<<<<< HEAD
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blocks and Rocks
email: dannydwarren@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software developement is like playing with digital building blocks all day. My goal
  is to teach you about some of those individual blocks so you can develop amazing
  things. Maybe I'll throw in a post about rock climbing or mountain biking every once
  in a while too...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dannydwarren
github_username:  dannydwarren

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
=======
theme: jekyll-theme-tactile
>>>>>>> 93e70d3182ab9bbafa22a9ad17a827569d48e0f7
